// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// emdL1_impl
Rcpp::NumericVector emdL1_impl(Rcpp::NumericVector h1, Rcpp::NumericVector h2, Rcpp::List rparam);
RcppExport SEXP earthmovdist_emdL1_impl(SEXP h1SEXP, SEXP h2SEXP, SEXP rparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rparam(rparamSEXP);
    rcpp_result_gen = Rcpp::wrap(emdL1_impl(h1, h2, rparam));
    return rcpp_result_gen;
END_RCPP
}
